'use client';
import {useEffect,useState,type FormEvent} from 'react';import {Search,CheckCircle2,Clock3,Wrench,ShieldCheck,ArrowRight,AlertTriangle} from 'lucide-react';import Link from 'next/link';
type Booking={booking_number:string;service_name:string;preferred_date:string;preferred_time:string;status:string;updated_at:string;rejection_reason?:string|null};type History={from_status:string|null;to_status:string;note:string|null;created_at:string};
const labels=['PENDING','APPROVED','IN_PROGRESS','COMPLETED'];
export default function TrackPage(){const[booking,setBooking]=useState<Booking|null>(null),[history,setHistory]=useState<History[]>([]),[number,setNumber]=useState(''),[token,setToken]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 async function lookup(n=number,t=token){setLoading(true);setError('');try{const r=await fetch('/api/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookingNumber:n,token:t}),cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Booking not found.');setBooking(d.booking);setHistory(d.history||[])}catch(e){setBooking(null);setHistory([]);setError(e instanceof Error?e.message:'Unable to track booking.')}finally{setLoading(false)}}
 useEffect(()=>{const q=new URLSearchParams(location.search),n=q.get('booking'),t=q.get('token');if(n&&t){setNumber(n);setToken(t);void lookup(n,t)}},[]);
 function submit(e:FormEvent){e.preventDefault();void lookup(number,token)}
 const current=booking?.status||'';const activeIndex=labels.indexOf(current);const rejected=current==='REJECTED';
 return <section className="section track-page"><div className="container narrow"><div className="center-head"><div className="eyebrow">CUSTOMER TRACKING</div><h1>Track your TechFix booking.</h1><p>Use the booking number and secure tracking token from your confirmation link.</p></div><form className="form-card track-form" onSubmit={submit}><div className="field"><label>Booking number</label><input value={number} onChange={e=>setNumber(e.target.value.toUpperCase())} placeholder="TF-1001" autoComplete="off"/></div><div className="field"><label>Tracking token</label><input value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste your secure token" autoComplete="off"/></div>{error&&<p className="form-error">{error}</p>}<button className="btn btn-green" disabled={loading||!number||!token}>{loading?'Checking…':'Track booking'}<Search size={17}/></button></form>{booking&&<div className="form-card tracking-result"><div className="tracking-head"><div><div className="eyebrow">{booking.booking_number}</div><h2>{booking.service_name}</h2></div><span className={`status-pill ${current.toLowerCase()}`}>{current.replace('_',' ')}</span></div>{rejected?<div className="tracking-alert rejected"><AlertTriangle size={20}/><div><strong>Booking not approved</strong><p>{booking.rejection_reason||'The requested booking was rejected by TechFix.'}</p></div></div>:<div className="status-progress">{labels.map((s,i)=><div className={`status-step ${i<=activeIndex?'done':''} ${i===activeIndex?'current':''}`} key={s}><div className="status-dot">{i<activeIndex?<CheckCircle2 size={15}/>:i===activeIndex?<Clock3 size={15}/>:<span>{i+1}</span>}</div><span>{s.replace('_',' ')}</span></div>)}</div>}<div className="tracking-meta"><div><Wrench size={17}/><span>Service<br/><b>{booking.service_name}</b></span></div><div><Clock3 size={17}/><span>Scheduled<br/><b>{booking.preferred_date} · {booking.preferred_time.slice(0,5)}</b></span></div><div><ShieldCheck size={17}/><span>Last updated<br/><b>{new Date(booking.updated_at).toLocaleString()}</b></span></div></div><div className="timeline">{history.map((h,i)=><div className="timeline-item" key={`${h.created_at}-${i}`}><span className="timeline-dot"/><div><b>{h.to_status.replace('_',' ')}</b><small>{new Date(h.created_at).toLocaleString()}</small>{h.note&&<p>{h.note}</p>}</div></div>)}</div></div>}<div className="center-head track-help"><p>Need help with your booking?</p><Link href="/book" className="text-link">Start another booking <ArrowRight size={16}/></Link></div></div></section>}
