'use client';
import {FormEvent,useState} from 'react';
import {Upload,CheckCircle2,ShieldCheck,ArrowLeft} from 'lucide-react';
import Link from 'next/link';

export default function TechnicianApply(){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const r=await fetch('/api/technician-applications',{method:'POST',body:form});const d=await r.json();if(r.ok)setDone(true);else setError(d.error||'Ubusabe ntibwoherejwe.');setBusy(false)}
 if(done)return <section className="section"><div className="container narrow"><div className="form-card success-card"><CheckCircle2 size={44}/><div className="eyebrow">TECHNICIAN APPLICATION</div><h1>Ubusabe bwoherejwe.</h1><p>Admin azabanza gusuzuma payment proof yawe. Niyemezwa, account ya Technician izakorwa kuri email watanze.</p><Link className="btn btn-green" href="/technician/login">Jya kuri Technician Login</Link></div></div></section>;
 return <section className="section"><div className="container narrow"><Link className="text-link" href="/technician/login"><ArrowLeft size={15}/> Technician Login</Link><div className="section-head"><div><div className="eyebrow">BECOME A TECHNICIAN</div><h1>Usabe access ya Technician.</h1><p className="muted">Amafaranga yo kwiyandikisha ni <b>30,000 FRW</b>, ntasubizwa. Admin ni we wemeza ubusabe nyuma yo kubona payment proof.</p></div></div><div className="payment-box"><b>MoMo Pay</b><strong>*182*8*1*935237#</strong><span>VINCENT · 30,000 FRW</span></div>{error&&<p className="form-error">{error}</p>}<form className="form-card" onSubmit={submit}><div className="field"><label>Amazina yuzuye</label><input name="fullName" required maxLength={120}/></div><div className="field"><label>Telephone / Sale Contact</label><input name="phone" required inputMode="tel" maxLength={40}/></div><div className="field"><label>Email</label><input name="email" type="email" required maxLength={160}/></div><div className="field"><label>Specialty <span>— optional</span></label><input name="specialty" placeholder="Laptop, Printer, Windows..." maxLength={160}/></div><div className="field"><label>Payment proof</label><label className="upload-box"><Upload size={20}/><span>Hitamo screenshot/photo ya payment cyangwa PDF</span><input name="paymentProof" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></label><small>Max 5MB.</small></div><div className="field"><label>Andi makuru <span>— optional</span></label><textarea name="notes" rows={4} maxLength={1000}/></div><button className="btn btn-green" disabled={busy}>{busy?'Ohereza...':'Ohereza ubusabe'}</button></form><div className="security-note"><ShieldCheck size={18}/><span>Payment proof isuzumwa na Admin. Nta account ihabwa access mbere yo kwemezwa.</span></div></div></section>
}
