'use client';
import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, PlayCircle, XCircle, LogOut, RefreshCw, Search, UserRound, ChevronDown, ClipboardList } from 'lucide-react';
import { useRouter } from 'next/navigation';

type Technician={id:string;name:string;phone?:string|null;email?:string|null;active:boolean};
type History={id:string;from_status:string|null;to_status:string;note:string|null;changed_by:string|null;created_at:string};
type Booking={id:string;booking_number:string;service_name:string;preferred_date:string;preferred_time:string;customer_name:string;customer_phone:string;notes?:string|null;status:string;technician_id?:string|null;technicians?:Technician|null;created_at:string;admin_note?:string|null};

const labels:Record<string,string>={PENDING:'Pending',APPROVED:'Approved',REJECTED:'Rejected',IN_PROGRESS:'In progress',COMPLETED:'Completed'};

export default function Admin(){
 const router=useRouter(); const [rows,setRows]=useState<Booking[]>([]),[techs,setTechs]=useState<Technician[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('ALL'),[service,setService]=useState('ALL'),[expanded,setExpanded]=useState(''),[history,setHistory]=useState<Record<string,History[]>>({});
 async function load(){setLoading(true);setError('');const [br,tr]=await Promise.all([fetch('/api/bookings'),fetch('/api/technicians')]);if(br.status===401){router.replace('/admin/login');return}const bd=await br.json();if(br.ok)setRows(bd.bookings||[]);else setError(bd.error||'Unable to load bookings.');if(tr.ok){const td=await tr.json();setTechs(td.technicians||[])}setLoading(false)}
 useEffect(()=>{void load()},[]);
 const services=useMemo(()=>Array.from(new Set(rows.map(r=>r.service_name))).sort(),[rows]);
 const stats=useMemo(()=>({total:rows.length,pending:rows.filter(r=>r.status==='PENDING').length,active:rows.filter(r=>r.status==='APPROVED'||r.status==='IN_PROGRESS').length,completed:rows.filter(r=>r.status==='COMPLETED').length}),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>{const q=search.toLowerCase();const matchesSearch=!q||[r.booking_number,r.customer_name,r.customer_phone,r.service_name].some(v=>String(v).toLowerCase().includes(q));return matchesSearch&&(status==='ALL'||r.status===status)&&(service==='ALL'||r.service_name===service)}),[rows,search,status,service]);
 async function action(id:string,payload:Record<string,unknown>){setBusy(id);setError('');const r=await fetch(`/api/bookings/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(r.status===401)router.replace('/admin/login');else if(r.ok)setRows(x=>x.map(v=>v.id===id?d.booking:v));else setError(d.error||'Unable to update booking.');setBusy('')}
 async function showHistory(id:string){if(expanded===id){setExpanded('');return}setExpanded(id);if(history[id])return;const r=await fetch(`/api/bookings/${id}`);if(r.ok){const d=await r.json();setHistory(h=>({...h,[id]:d.history||[]}))}}
 async function logout(){await fetch('/api/admin/logout',{method:'POST'});router.replace('/admin/login')}
 return <section className="section admin-page"><div className="container">
  <div className="section-head"><div><div className="eyebrow">TECHFIX ADMIN</div><h1>Booking control center.</h1><p className="muted">Review requests, assign technicians and move each job through its service lifecycle.</p></div><div className="hero-actions"><button className="btn btn-ghost" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button><button className="btn btn-dark" onClick={()=>void logout()}><LogOut size={16}/>Sign out</button></div></div>
  {error&&<p role="alert" className="error-text">{error}</p>}
  <div className="stats-grid"><div className="stat-card"><span>Total</span><strong>{stats.total}</strong><small>All bookings</small></div><div className="stat-card"><span>Pending</span><strong>{stats.pending}</strong><small>Need review</small></div><div className="stat-card"><span>Active</span><strong>{stats.active}</strong><small>Approved / in progress</small></div><div className="stat-card"><span>Completed</span><strong>{stats.completed}</strong><small>Finished jobs</small></div></div>
  <div className="admin-toolbar"><label className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search booking, customer or phone"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={service} onChange={e=>setService(e.target.value)}><option value="ALL">All services</option>{services.map(v=><option key={v}>{v}</option>)}</select></div>
  <div className="booking-list">{loading?<div className="form-card">Loading bookings…</div>:filtered.length===0?<div className="form-card empty-state"><ClipboardList size={30}/><h3>No matching bookings</h3><p>Try another search or filter.</p></div>:filtered.map(row=><article key={row.id} className="booking-card">
   <div className="booking-main"><div><span className="booking-number">{row.booking_number}</span><h3>{row.service_name}</h3><p>{row.customer_name} · {row.customer_phone}</p><p>{row.preferred_date} · {String(row.preferred_time).slice(0,5)}</p></div><span className={`status ${row.status}`}>{labels[row.status]||row.status}</span></div>
   <div className="booking-meta"><div><UserRound size={15}/><select aria-label="Assign technician" value={row.technician_id||''} disabled={busy===row.id} onChange={e=>void action(row.id,{technicianId:e.target.value||null})}><option value="">Unassigned</option>{techs.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><button className="text-button" onClick={()=>void showHistory(row.id)}>{expanded===row.id?'Hide timeline':'View timeline'}<ChevronDown size={15}/></button></div>
   {expanded===row.id&&<div className="timeline">{history[row.id]?.length?history[row.id].map(h=><div className="timeline-item" key={h.id}><span className="timeline-dot"/><div><b>{labels[h.to_status]||h.to_status}</b><small>{new Date(h.created_at).toLocaleString()} · {h.changed_by||'SYSTEM'}</small>{h.note&&<p>{h.note}</p>}</div></div>):<p className="muted">Loading timeline…</p>}</div>}
   {row.notes&&<p className="booking-notes"><b>Customer note:</b> {row.notes}</p>}
   <div className="hero-actions booking-actions">{row.status==='PENDING'&&<><button className="btn btn-green" disabled={busy===row.id} onClick={()=>void action(row.id,{status:'APPROVED'})}><CheckCircle2 size={15}/>Approve</button><button className="btn btn-dark" disabled={busy===row.id} onClick={()=>void action(row.id,{status:'REJECTED',note:'Rejected by admin'})}><XCircle size={15}/>Reject</button></>}{row.status==='APPROVED'&&<button className="btn btn-green" disabled={busy===row.id} onClick={()=>void action(row.id,{status:'IN_PROGRESS'})}><PlayCircle size={15}/>Start Service</button>}{row.status==='IN_PROGRESS'&&<button className="btn btn-green" disabled={busy===row.id} onClick={()=>void action(row.id,{status:'COMPLETED'})}><CheckCircle2 size={15}/>Mark Completed</button>}</div>
  </article>)}</div>
 </div></section>
}