import {NextResponse} from 'next/server';
import {getSupabaseAdmin} from '@/lib/supabase';

function clean(v:unknown,max=120){return typeof v==='string'?v.trim().slice(0,max):''}
function score(tech:any,province:string,district:string,sector:string,cell:string){let s=0;if(province&&tech.province?.toLowerCase()===province.toLowerCase())s+=10;if(district&&tech.district?.toLowerCase()===district.toLowerCase())s+=30;if(sector&&tech.sector?.toLowerCase()===sector.toLowerCase())s+=50;if(cell&&tech.cell?.toLowerCase()===cell.toLowerCase())s+=70;return s}

export async function GET(request:Request){try{const{searchParams}=new URL(request.url);const province=clean(searchParams.get('province'));const district=clean(searchParams.get('district'));const sector=clean(searchParams.get('sector'));const cell=clean(searchParams.get('cell'));const serviceSlug=clean(searchParams.get('serviceSlug'),80);if(!province&&!district&&!sector&&!cell)return NextResponse.json({error:'Location is required to find nearby technicians.'},{status:400});const db=getSupabaseAdmin();const{data:techs,error}=await db.from('technicians').select('id,name,full_name,phone,email,active,province,district,sector,cell,address,google_maps_url,latitude,longitude,service_radius_km,specialties').eq('active',true).order('name');if(error)return NextResponse.json({error:error.message},{status:500});let service:any=null;if(serviceSlug){const r=await db.from('services').select('slug,name,category_slug').eq('slug',serviceSlug).maybeSingle();if(r.error)return NextResponse.json({error:r.error.message},{status:500});service=r.data}
const result=(techs??[]).map((t:any)=>{const matchScore=score(t,province,district,sector,cell);const specialties=Array.isArray(t.specialties)?t.specialties:[];const specialtyMatch=!service||specialties.length===0||specialties.some((x:string)=>x===service.slug||x===service.category_slug);return{...t,name:t.name||t.full_name||'Technician',location_match_score:matchScore,specialty_match:specialtyMatch}}).filter((t:any)=>t.location_match_score>0).sort((a:any,b:any)=>b.location_match_score-a.location_match_score||String(a.name).localeCompare(String(b.name))).map(({password_hash,password_salt,...safe}:any)=>safe);
return NextResponse.json({technicians:result,location:{province,district,sector,cell}},{headers:{'Cache-Control':'no-store'}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to find technicians.'},{status:500})}}
