import { NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/lib/supabase';
import { isAdminSession } from '@/lib/admin-auth';
import { allITServices } from '@/lib/it-services';

async function ensureCatalog(db:any){
  const {data:existing,error}=await db.from('services').select('id,slug,category_slug').in('slug',allITServices.map(s=>s.slug));
  if(error)throw new Error(error.message);
  const bySlug=new Map((existing??[]).map((s:any)=>[s.slug,s]));
  const missing=allITServices.filter(s=>!bySlug.has(s.slug)).map((s,i)=>({slug:s.slug,name:s.name,description:s.description,active:true,published:true,category_slug:s.categorySlug,category_name:s.categoryName,category_name_rw:s.categoryNameRW,name_rw:s.nameRW,description_rw:s.descriptionRW,price_type:s.priceType,currency:'RWF',estimated_duration_minutes:s.durationMinutes??null,booking_methods:s.methods,image:s.image??null,sort_order:i}));
  if(missing.length){const {error:insertError}=await db.from('services').insert(missing);if(insertError)throw new Error(insertError.message);}
  for(const s of allITServices){const current=bySlug.get(s.slug);if(current?.category_slug)continue;const {error:updateError}=await db.from('services').update({category_slug:s.categorySlug,category_name:s.categoryName,category_name_rw:s.categoryNameRW,name_rw:s.nameRW,description_rw:s.descriptionRW,price_type:s.priceType,currency:'RWF',estimated_duration_minutes:s.durationMinutes??null,booking_methods:s.methods,image:s.image??null,sort_order:allITServices.indexOf(s)}).eq('slug',s.slug);if(updateError)throw new Error(updateError.message)}
}

export async function GET(){if(!(await isAdminSession()))return NextResponse.json({error:'Unauthorized'},{status:401});try{const db=getSupabaseAdmin();await ensureCatalog(db);const {data,error}=await db.from('services').select('id,slug,name,name_rw,description,description_rw,active,published,category_slug,category_name,category_name_rw,price_type,min_price,max_price,currency,estimated_duration_minutes,booking_methods,image,sort_order,created_at').order('sort_order').order('created_at');if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({services:data||[]},{headers:{'Cache-Control':'no-store'}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to load services.'},{status:500})}}

export async function POST(request:Request){if(!(await isAdminSession()))return NextResponse.json({error:'Unauthorized'},{status:401});try{const b=await request.json();const name=typeof b.name==='string'?b.name.trim().slice(0,120):'';const description=typeof b.description==='string'?b.description.trim().slice(0,500):'';const slug=typeof b.slug==='string'?b.slug.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80):'';if(!name||!description||!slug)return NextResponse.json({error:'Name, slug and description are required.'},{status:400});const {data,error}=await getSupabaseAdmin().from('services').insert({name,slug,description,active:true,price_type:'QUOTE',currency:'RWF',booking_methods:['CENTER']}).select('id,slug,name,name_rw,description,description_rw,active,published,category_slug,category_name,category_name_rw,price_type,min_price,max_price,currency,estimated_duration_minutes,booking_methods,image,sort_order,created_at').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({service:data},{status:201});}catch{ return NextResponse.json({error:'Invalid request.'},{status:400});}}

export async function PATCH(request:Request){if(!(await isAdminSession()))return NextResponse.json({error:'Unauthorized'},{status:401});try{const b=await request.json();if(typeof b.id!=='string')return NextResponse.json({error:'Service id required.'},{status:400});const patch:any={};if(typeof b.name==='string')patch.name=b.name.trim().slice(0,120);if(typeof b.description==='string')patch.description=b.description.trim().slice(0,500);if(typeof b.active==='boolean')patch.active=b.active;if(typeof b.published==='boolean')patch.published=b.published;if(typeof b.priceType==='string')patch.price_type=b.priceType;if(Number.isInteger(b.minPrice))patch.min_price=b.minPrice;if(Number.isInteger(b.maxPrice))patch.max_price=b.maxPrice;if(typeof b.currency==='string')patch.currency=b.currency.slice(0,8);if(Number.isInteger(b.durationMinutes))patch.estimated_duration_minutes=b.durationMinutes;if(Array.isArray(b.bookingMethods))patch.booking_methods=b.bookingMethods;if(typeof b.image==='string')patch.image=b.image.slice(0,500);if(Number.isInteger(b.sortOrder))patch.sort_order=b.sortOrder;const {data,error}=await getSupabaseAdmin().from('services').update(patch).eq('id',b.id).select('id,slug,name,name_rw,description,description_rw,active,published,category_slug,category_name,category_name_rw,price_type,min_price,max_price,currency,estimated_duration_minutes,booking_methods,image,sort_order,created_at').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({service:data});}catch{return NextResponse.json({error:'Invalid request.'},{status:400});}}
