import Image from 'next/image';
import Link from 'next/link';
import { CheckCircle2, Clock3, ShieldCheck, Wrench, ArrowRight, MessageCircle } from 'lucide-react';
import { services } from '@/lib/services';
import { Button } from '@/components/Button';
export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow">PROFESSIONAL IT SERVICE BOOKING</div><h1>We Repair.<br/><span>We Install.</span><br/>We Solve IT.</h1><p>Book trusted technical service for laptops, Windows, crashed PCs, printers and other IT problems.</p><div className="hero-actions"><Button href="/book">Book a Service</Button><Link href="#services" className="text-link">Explore services <ArrowRight size={17}/></Link></div><div className="hero-trust"><span><CheckCircle2 size={17}/> Clear estimates</span><span><Clock3 size={17}/> Status updates</span><span><ShieldCheck size={17}/> Professional care</span></div></div><div className="hero-media"><Image src="https://images.pexels.com/photos/33531806/pexels-photo-33531806.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Technician repairing a laptop" fill priority sizes="(max-width:900px) 100vw,50vw"/><div className="hero-badge"><span className="badge-dot"/> Booking available<br/><strong>Choose a service &amp; slot</strong></div></div></div></section>
<section id="services" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">OUR SERVICES</div><h2>Technical help that starts with a booking.</h2></div><Link href="/book" className="outline-link">View all &amp; book <ArrowRight size={16}/></Link></div><div className="service-grid">{services.map(s=><article className="service-card" key={s.slug}><div className="service-image"><Image src={s.image} alt={s.name} fill sizes="(max-width:700px) 100vw,33vw"/><span className={`service-chip ${s.accent}`}>{s.shortName}</span></div><div className="service-body"><h3>{s.name}</h3><p>{s.description}</p><Link href={`/services/${s.slug}`} className="card-link">View service <ArrowRight size={16}/></Link></div></article>)}</div></div></section>
<section id="how-it-works" className="section process-section"><div className="container"><div className="center-head"><div className="eyebrow">HOW IT WORKS</div><h2>Four simple steps. Zero confusion.</h2><p>Our booking flow keeps customers informed and gives technicians the right information before work starts.</p></div><div className="steps">{[['01','Choose a service','Tell us what you need repaired or installed.'],['02','Pick a slot','Select your preferred date and time.'],['03','Confirm details','Add contact details and problem notes.'],['04','We handle it','Get approval, status updates and completion notice.']].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section id="why-us" className="section"><div className="container why-grid"><div className="why-image"><Image src="https://images.pexels.com/photos/34404168/pexels-photo-34404168.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Technician working on electronic equipment" fill sizes="(max-width:900px) 100vw,50vw"/></div><div><div className="eyebrow">WHY TECHFIX</div><h2>Professional service with a smarter booking experience.</h2><p className="lead">Every booking follows a clear service status so customers and technicians stay aligned.</p><div className="why-list">{[['Smart booking flow','Progressive form with clear availability.'],['State-based actions','Admin actions change with booking status.'],['Real service photos','No AI-generated service photography.'],['Mobile-first','Fast and easy to book from a phone.']].map(([t,d])=><div className="why-item" key={t}><div className="why-icon"><Wrench size={19}/></div><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><Button href="/book">Start your booking</Button></div></div></section>
<section className="cta-section"><div className="container cta-box"><div><div className="eyebrow">NEED HELP NOW?</div><h2>Describe the problem. We’ll take it from there.</h2><p>Use the booking form and give the technician enough context to prepare.</p></div><Button href="/book" variant="yellow">Book a Service</Button></div></section><a className="whatsapp" href="https://wa.me/250786513474" target="_blank" rel="noreferrer"><MessageCircle size={22}/><span>WhatsApp</span></a></>}
