export type Service={slug:string;name:string;shortName:string;description:string;details:string[];problems:string[];image:string;accent:'green'|'yellow'};
export const services:Service[]=[
{slug:'laptop-repair',name:'Laptop Repair',shortName:'Laptop Repair',description:'Hardware diagnostics, screen, keyboard, charging and motherboard repair.',details:['Full hardware diagnosis','Component-level repair','Screen, keyboard & charging issues','Clear estimate before work starts'],problems:['Broken or cracked screen','Laptop not charging','Keyboard or touchpad failure','Overheating / motherboard issues'],image:'https://images.pexels.com/photos/28380001/pexels-photo-28380001.jpeg?auto=compress&cs=tinysrgb&w=1200',accent:'green'},
{slug:'windows-installation',name:'Windows Installation',shortName:'Windows Install',description:'Clean Windows installation, drivers, updates and essential setup.',details:['Windows installation & activation guidance','Drivers and updates','Basic software setup','Performance check'],problems:['Windows not starting','Slow or unstable system','Fresh Windows setup','Missing drivers after installation'],image:'https://images.pexels.com/photos/31869847/pexels-photo-31869847.jpeg?auto=compress&cs=tinysrgb&w=1200',accent:'yellow'},
{slug:'crashed-pc-recovery',name:'Crashed PC Recovery',shortName:'PC Recovery',description:'Recover unstable, slow or crashed computers and get your workflow back.',details:['System diagnosis','Boot & startup recovery','Data-safe troubleshooting','Performance optimization'],problems:['PC freezes or crashes','Blue-screen / startup failure','Very slow computer','Boot or system errors'],image:'https://images.pexels.com/photos/6754846/pexels-photo-6754846.jpeg?auto=compress&cs=tinysrgb&w=1200',accent:'green'},
{slug:'printer-repair',name:'Printer Repair',shortName:'Printer Repair',description:'Printer troubleshooting, maintenance and hardware repair for office and home devices.',details:['Paper-feed & print-quality diagnosis','Hardware maintenance','Connectivity troubleshooting','Printer testing'],problems:['Paper jams / feed problems','Poor print quality','Printer not detected','Mechanical or internal faults'],image:'https://images.pexels.com/photos/37492296/pexels-photo-37492296.jpeg?auto=compress&cs=tinysrgb&w=1200',accent:'yellow'},
{slug:'inkpad-resolution',name:'InkPad Resolution',shortName:'InkPad Resolution',description:'Resolve supported Epson InkPad / waste-ink service errors and restore printing.',details:['Error diagnosis','Supported service reset workflow','Print test after service','Clear next-step guidance'],problems:['Waste-ink / InkPad warning','Service-required message','Printer stops printing','Ink system service errors'],image:'https://images.pexels.com/photos/14098466/pexels-photo-14098466.jpeg?auto=compress&cs=tinysrgb&w=1200',accent:'green'},
{slug:'other-it-services',name:'Other IT Services',shortName:'Other IT',description:'Need something else? Tell us what is wrong and we will review the job before approval.',details:['Custom IT diagnosis','Software troubleshooting','Device setup','Business support requests'],problems:['Software problems','Device setup needs','Network / connectivity issues','Other IT faults'],image:'https://images.pexels.com/photos/34404168/pexels-photo-34404168.jpeg?auto=compress&cs=tinysrgb&w=1200',accent:'yellow'}];
export function getService(slug:string){return services.find(s=>s.slug===slug)}
