import { NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/lib/supabase';
import { isAdminSession } from '@/lib/admin-auth';
const fields='id,name,full_name,phone,email,active,auth_user_id,province,district,sector,cell,address,google_maps_url,latitude,longitude,service_radius_km,specialties';
function text(v:unknown,max=200){return typeof v==='string'?v.trim().slice(0,max):null}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null}
export async function GET(){if(!(await isAdminSession()))return NextResponse.json({error:'Unauthorized'},{status:401});const {data,error}=await getSupabaseAdmin().from('technicians').select(fields).order('name');if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({technicians:data??[]});}
export async function POST(request:Request){if(!(await isAdminSession()))return NextResponse.json({error:'Unauthorized'},{status:401});try{const body=await request.json();const name=typeof body.name==='string'?body.name.trim().slice(0,120):'';const phone=text(body.phone,40);const email=typeof body.email==='string'?body.email.trim().toLowerCase().slice(0,160):'';const password=typeof body.password==='string'?body.password:'';if(!name||!email||password.length<8)return NextResponse.json({error:'Name, email and password (8+ chars) are required.'},{status:400});const specialties=Array.isArray(body.specialties)?body.specialties.filter((x:unknown):x is string=>typeof x==='string').map((x:string)=>x.trim()).filter(Boolean).slice(0,30):[];const location={province:text(body.province,80),district:text(body.district,80),sector:text(body.sector,80),cell:text(body.cell,80),address:text(body.address,300),google_maps_url:text(body.googleMapsUrl,500),latitude:num(body.latitude),longitude:num(body.longitude),service_radius_km:num(body.serviceRadiusKm)??10,specialties};const admin=getSupabaseAdmin();const created=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{role:'TECHNICIAN',full_name:name}});if(created.error||!created.data.user)return NextResponse.json({error:created.error?.message||'Unable to create login.'},{status:500});const {data,error}=await admin.from('technicians').insert({name,phone,email,active:true,auth_user_id:created.data.user.id,...location}).select(fields).single();if(error){await admin.auth.admin.deleteUser(created.data.user.id);return NextResponse.json({error:error.message},{status:500});}return NextResponse.json({technician:data},{status:201});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to create technician.'},{status:500});}}
export async function PATCH(request:Request){if(!(await isAdminSession()))return NextResponse.json({error:'Unauthorized'},{status:401});try{const body=await request.json();const id=Number(body.id);if(!Number.isFinite(id))return NextResponse.json({error:'Technician id is required.'},{status:400});const patch:any={};for(const key of ['province','district','sector','cell','address'])if(typeof body[key]==='string')patch[key]=body[key].trim().slice(0,300);if(typeof body.googleMapsUrl==='string')patch.google_maps_url=body.googleMapsUrl.trim().slice(0,500);for(const key of ['latitude','longitude','serviceRadiusKm'])if(body[key]!==undefined){const n=num(body[key]);if(n!==null)patch[key==='serviceRadiusKm'?'service_radius_km':key]=n}if(Array.isArray(body.specialties))patch.specialties=body.specialties.filter((x:unknown):x is string=>typeof x==='string').map((x:string)=>x.trim()).filter(Boolean).slice(0,30);if(typeof body.active==='boolean')patch.active=body.active;const{data,error}=await getSupabaseAdmin().from('technicians').update(patch).eq('id',id).select(fields).single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({technician:data})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to update technician.'},{status:400})}}
